name: ISO

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build container and ISO
        run: sudo make ARCH=amd64 DISK_TYPE=anaconda-iso oci-image disk-image 
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: output/bootiso/install.iso
